---
- name: Verify
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: install pip module
      ansible.builtin.pip:
        name: docker
        state: present
      when:
        - ansible_distribution_release != "bookworm"

    - name: check if bootstrap still works.
      ansible.builtin.include_role:
        name: robertdebock.bootstrap

    - name: remove pip module
      ansible.builtin.pip:
        name: docker
        state: absent
      when:
        - ansible_distribution_release != "bookworm"

    - name: check if requested modules can be installed
      ansible.builtin.include_role:
        name: ansible-role-python_pip
      vars:
        python_pip_modules:
          - name: docker

    - name: check if requested modules can be removed
      ansible.builtin.include_role:
        name: ansible-role-python_pip
      vars:
        python_pip_modules:
          - name: docker
            state: absent

    - name: check if pyOpenSSL can be installed
      ansible.builtin.pip:
        name: pyOpenSSL
        state: present
      notify:
        - remove pyOpenSSL
      when:
        - ansible_distribution_release != "bookworm"

  handlers:
    - name: remove pyOpenSSL
      ansible.builtin.pip:
        name: pyOpenSSL
        state: absent
