---
- name: Verify
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: install pip module
      pip:
        name: ansible
        state: present

    - name: check if bootstrap still works.
      include_role:
        name: robertdebock.bootstrap

  roles:
    - role: ansible-role-python_pip
      python_pip_modules:
        - name: ansible
