---
- name: Verify
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Install pip package (try without flags)
      notify:
        - Remove pip package
      block:
        - name: Install pip package
          ansible.builtin.pip:
            name: docker
      rescue:
        - name: Retry install with --break-system-packages when supported
          ansible.builtin.pip:
            name: docker
            break_system_packages: true
            extra_args: --break-system-packages

    - name: Check if bootstrap still works.
      ansible.builtin.include_role:
        name: robertdebock.bootstrap

  handlers:
    - name: Remove pip package
      ansible.builtin.pip:
        name: docker
        state: absent
