---
- name: Verify
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Install pip module
      ansible.builtin.pip:
        name: docker
        state: present
        break_system_packages: true
        extra_args: --break-system-packages

    - name: Check if bootstrap still works.
      ansible.builtin.include_role:
        name: robertdebock.bootstrap

    - name: Remove pip module
      ansible.builtin.pip:
        name: docker
        state: absent
        break_system_packages: true
        extra_args: --break-system-packages
