---
- name: Verify
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Install pip module
      ansible.builtin.pip:
        name: docker
      notify: Remove pip module

    - name: Check if bootstrap still works.
      ansible.builtin.include_role:
        name: robertdebock.bootstrap

  handlers:
    - name: Remove pip module
      ansible.builtin.pip:
        name: docker
        state: absent
