---
- name: Verify
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Install pip module
      ansible.builtin.pip:
        name: docker
        state: present
      when:
        - ansible_distribution_release != "noble"
        - ansible_os_family != "Alpine"

    - name: Check if bootstrap still works.
      ansible.builtin.include_role:
        name: robertdebock.bootstrap

    - name: Remove pip module
      ansible.builtin.pip:
        name: docker
        state: absent
      when:
        - ansible_distribution_release != "noble"
        - ansible_os_family != "Alpine"

    - name: Check if requested modules can be installed
      ansible.builtin.include_role:
        name: ansible-role-python_pip
      vars:
        python_pip_modules:
          - name: Docker

    - name: Check if requested modules can be removed
      ansible.builtin.include_role:
        name: ansible-role-python_pip
      vars:
        python_pip_modules:
          - name: Docker
            state: absent

    - name: Check if pyOpenSSL can be installed
      ansible.builtin.pip:
        name: pyOpenSSL
        state: present
      notify:
        - Remove pyOpenSSL
      when:
        - ansible_distribution_release != "noble"
        - ansible_os_family != "Alpine"

  handlers:
    - name: Remove pyOpenSSL
      ansible.builtin.pip:
        name: pyOpenSSL
        state: absent
